### ISSUE TITLE
Changes work great!

### ISSUE THREAD

**Issue by drelatgithub** [Dguto9/Hexagon-Wallpaper#1]
Thank you so much for your interest in this wallpaper. I tested your changes locally and they really work amazing! I am wondering if it is possible to fork and create a pull request to <https://github.com/drelatgithub/HexagonWallpaper>? I made some updates on the master branch reflecting previous updates as well.

**Comment by Dguto9** [comment]
Of course! I do not know my way around GitHub very well yet but I will try to make a pull request to the repository. When I acquire better hardware at some point soon, I would love to work on adding LED integrations.

**Comment by drelatgithub** [comment]
Thank you for this! I've incorporated the changes and uploaded the new version to workshop.
